# Jekyll configuration for Practical Meta AudioCraft book

# Site settings
title: "Practical Meta AudioCraft"
tagline: "Building AI Audio Generation Systems"
description: "A hands-on guide to creating music, sound effects, and audio experiences with AI"
url: "https://scttfrdmn.github.io"
baseurl: "/practical-meta-audiocraft"
repository: "scttfrdmn/practical-meta-audiocraft"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - CLAUDE.md
  - DEVELOPMENT_PLAN.md

# Theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-redirect-from

# Custom settings
book:
  author: "Scott Friedman"
  version: "1.0.0"
  github_repo: "https://github.com/facebookresearch/audiocraft"
  copyright_year: "2025"
  license: "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License"

# Table of contents
collections:
  chapters:
    output: true
    permalink: /:collection/:path/

# Default settings for different content types
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "default"
      nav_order: 1
      has_children: false
      parent: ""
      nav_exclude: false
  - scope:
      path: "assets/images"
    values:
      image: true

# Navigation structure
nav:
  - title: Home
    url: /
  - title: "Part I: Foundations"
    url: /chapters/part1/
    children:
      - title: "1. Introduction to AI Audio Generation"
        url: /chapters/part1/introduction/
      - title: "2. Setting Up Your Environment"
        url: /chapters/part1/setup/
      - title: "3. Understanding AudioCraft Architecture"
        url: /chapters/part1/architecture/
      - title: "4. Your First Audio Generation"
        url: /chapters/part1/first-generation/
  - title: "Part II: Music Generation with MusicGen"
    url: /chapters/part2/
    children:
      - title: "5. Basic Music Generation"
        url: /chapters/part2/basic-music/
      - title: "6. Prompt Engineering for Music"
        url: /chapters/part2/prompt-engineering/
      - title: "7. Parameter Optimization"
        url: /chapters/part2/parameter-optimization/
      - title: "8. Melody Conditioning"
        url: /chapters/part2/melody-conditioning/
      - title: "9. Advanced Music Generation Techniques"
        url: /chapters/part2/advanced-techniques/
  - title: "Part III: Sound Effects with AudioGen"
    url: /chapters/part3/
    children:
      - title: "10. Basic Sound Effect Generation"
        url: /chapters/part3/basic-sound-effects/
      - title: "11. Crafting Sound Effect Prompts"
        url: /chapters/part3/sound-prompts/
      - title: "12. Building Sound Libraries"
        url: /chapters/part3/sound-libraries/
      - title: "13. Creating Complex Soundscapes"
        url: /chapters/part3/complex-soundscapes/
  - title: "Part IV: Integration and Deployment"
    url: /chapters/part4/
    children:
      - title: "14. Building Web Interfaces"
        url: /chapters/part4/web-interfaces/
      - title: "15. Creating REST APIs"
        url: /chapters/part4/rest-apis/
      - title: "16. Containerization with Docker"
        url: /chapters/part4/docker/
      - title: "17. Performance Optimization and Scaling"
        url: /chapters/part4/optimization/
  - title: "Part V: Advanced Applications"
    url: /chapters/part5/
    children:
      - title: "18. Building a Complete Audio Pipeline"
        url: /chapters/part5/audio-pipeline/
      - title: "19. Text-to-Speech Integration"
        url: /chapters/part5/tts-integration/
      - title: "20. Interactive Audio Systems"
        url: /chapters/part5/interactive-systems/
      - title: "21. Research Extensions and Future Directions"
        url: /chapters/part5/future-directions/

# Custom variables
audiocraft_version: "1.0.0"
min_python_version: "3.9"
recommended_pytorch_version: "2.1.0"